clf
clear
FileNA={'Pt01','Pt02','Pt03','Pt04','Pt05','Pt06','Pt07','Pt08','Pt09','Chang'}
% FileNA={'NP03_B02_g0_t0',...
% 'NP04_B2_g0_t0',...
% 'NP10_B2_g0_t0',...
% 'NP10_B3_g0_t0',...
% 'NP10_B4_g0_t0',...
% 'NP11_B4_g0_t0',...
% 'NP12_g0_tcat',...
% 'NP13_B2_g0_t0',...
% 'NP14_B2_g0_t0',...
% 'NP14_B3_g0_t0',...
% 'NP15_B2_g0_t0'};

for ns=1:length(FileNA)
subplot(1,10,ns)
if ns<10
    load(['E:\',FileNA{ns},'\',FileNA{ns},'_ChannelMap.mat'],'xcoords','ycoords')
else
    load(['E:\',FileNA{7},'\',FileNA{7},'_ChannelMap.mat'],'xcoords','ycoords')

end

    scatter(xcoords,...
        ycoords,48,"black",'marker','s')
    hold on
%     text(xcoords,...
%         ycoords,...
%         num2str((1:length(xcoords))'))
    xcoords=xcoords';
    ycoords=ycoords';
    title(FileNA{ns})
    ylim([0 8000])
    set(gca,'fontsize',12)
    if ns==1
    ylabel('depth (microns), with 0 the deepest contact')
    end
end

